name: build

on:
  # pull_request:
  # push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    env:
      NUPKG_MAJOR: 0.1
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Restore Dependencies
      working-directory: src/Plugin.InAppBilling
      run: |
        dotnet workload restore 
        dotnet restore

    - name: Build
      working-directory: src/Plugin.InAppBilling
      run: dotnet build --no-restore --configuration Release

   # - name: Test
   #   run: dotnet test --configuration Release

    - name: Package NuGets
      working-directory: src/Plugin.InAppBilling
      shell: pwsh
      run: |
        $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
        if ($env:GITHUB_EVENT_NAME -eq "release") {
          $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/v') + 2)
        }
        echo "$env:GITHUB_REF"
        echo "PACKAGE VERSION: $VERSION"
        
        dotnet pack --no-build -p:PackageOutputPath=../../artifacts -p:Configuration=Release -p:PackageVersion=$VERSION ./Plugin.InAppBilling.csproj

    - name: Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: NuGet
        path: ./artifacts

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: NuGet

      - name: Push NuGet
        run: |
          dotnet nuget push NuGet/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_PROJECT_API_KEY }}