name: build

on:
  # pull_request:
  # push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    env:
      NUPKG_MAJOR: 0.1
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

   # - name: Test
   #   run: dotnet test --configuration Release
    - name: Package NuGets
      shell: pwsh
      run: |
        $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
        if ($env:GITHUB_EVENT_NAME -eq "release") {
          $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
        }
        echo "::set-output name=pkgverci::$VERSION"
        echo "PACKAGE VERSION: $VERSION"
        
        dotnet pack -p:PackageOutputPath=./artifacts -p:Configuration=Release -p:PackageVersion=$VERSION ./src/Plugin.InAppBilling/Plugin.InAppBilling.csproj

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet
        path: ./artifacts

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
      - name: Push NuGet
        run: |
          dotnet nuget push NuGet\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_PROJECT_API_KEY }}